apiVersion: apps/v1
kind: Deployment
metadata:
  name: virusscannerservice
  namespace: dpm
  labels:
    app: virusscannerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virusscannerservice
  template:
    metadata:
      labels:
        app: virusscannerservice
    spec:
      restartPolicy: Always
      containers:
      - name: virusscannerservice
        image: registry.vimuens.nl/virusscanner-api:1.1.5 # {"$imagepolicy": "flux-system:virusscanner-api-policy"}
        imagePullPolicy: Always
        env:
        - name: server.port
          value: "9095"
        ports:
        - containerPort: 8086
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
