apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: dpm
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      restartPolicy: Always
      containers:
      - name: gateway
        image: registry.vimuens.nl/dpm-gateway:1.0.5 # {"$imagepolicy": "flux-system:gateway-api-policy"}
        imagePullPolicy: Always
        env:
        - name: server.port
          value: "9090"
        - name: spring.cloud.kubernetes.discovery.enabled
          value: "true"
        - name: spring.cloud.kubernetes.reload.enabled
          value: "true"
        - name: spring.cloud.kubernetes.discovery.locator.enabled
          value: "true"
        ports:
        - containerPort: 8082
