apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: dpm
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      restartPolicy: Always
      containers:
        - name: gateway
          image: registry.vimuens.nl/dpm-gateway:1.0.0 # {"$imagepolicy": "flux-system:gateway-api-policy"}
          imagePullPolicy: Always
          env:
            - name: server.port
              value: "9090"
          ports:
            - containerPort: 8082
