apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: dpm
spec:
  ports:
  - protocol: TCP
      port: 8080
      targetPort: 9090
  selector:
    app: gateway
  type: NodePort
  - NodePort: 31235