apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: dpm
  labels:
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      restartPolicy: Always
      containers:
      - name: userservice
        image: registry.vimuens.nl/user-api:1.1.1 # {"$imagepolicy": "flux-system:user-api-policy"}
        imagePullPolicy: Always
        env:
        - name: server.port
          value: "9092"
        ports:
        - containerPort: 8083
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
