apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: userapihpa
  namespace: dpm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userservice
  maxReplicas: 5
  minReplicas: 1
  targetCPUUtilizationPercentage: 70
