apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: dpm
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 9090
      nodePort: 31235
  type: NodePort
